version: '3'

services:
  app:
    image: node:12
    working_dir: /app
    environment:
      PORT: 9955
      CHOKIDAR_USEPOLLING: '1'
    volumes:
      - ./app:/app
      - deps:/app/node_modules
    command: npm start
    ports:
      - 9955:9955

volumes:
  deps:
